# Generated by Django 4.2.7 on 2023-11-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('imagen', models.URLField(help_text='Cargar solo la url')),
                ('descripcion', models.TextField(help_text='Descripcion breve del jugador')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
